Fixed deployment file

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -10,23 +10,56 @@ pipeline {
             }
         }
 
-        stage('Pull Latest Code') {
+        stage('Show Current Containers') {
             steps {
-                sh 'git pull origin main || true'
+                sh 'docker ps -a || true'
             }
         }
 
-        stage('Build') {
+        stage('Build Images') {
             steps {
                 sh 'docker compose build'
             }
         }
 
+        stage('Cleanup Old Deployment') {
+            steps {
+                sh '''
+                docker compose down --remove-orphans || true
+
+                docker rm -f backend frontend 2>/dev/null || true
+
+                docker rm -f calculator-ci-cd-backend-1 calculator-ci-cd-frontend-1 2>/dev/null || true
+                '''
+            }
+        }
+
         stage('Deploy') {
             steps {
-                sh 'docker compose up -d --remove-orphans'
+                sh '''
+                docker compose up -d --build
+                '''
+            }
+        }
+
+        stage('Verify') {
+            steps {
+                sh '''
+                docker ps
+                '''
             }
         }
     }
-}
 
+    post {
+
+        success {
+            echo '✅ Deployment Successful'
+        }
+
+        failure {
+            echo '❌ Deployment Failed'
+            sh 'docker ps -a || true'
+        }
+    }
+}
